### ISSUE TITLE
Error in example (configFilesProvider)

### ISSUE THREAD

**Issue by lathspell** [cfg4j/cfg4j#123]
In http://www.cfg4j.org/#files

ConfigFilesProvider configFilesProvider = () -> Arrays.asList(new File("application.properties"), new File("otherConfig.properties"));

Java complaints that the infered type is "File" whereas the expected type is "Path".

**Comment by norbertpotocki** [comment]
Thanks for pointing this out @lathspell! It should be fixed now (replaced "new File()" with Paths.get())
