### ISSUE TITLE
Add support for Java 7

### ISSUE THREAD

**Issue by seaward** [cfg4j/cfg4j#127]
How can I make it run on JDK6 / 7 ?
Or there are old versions can run on JDK6? If yes, which version then?

Thanks!

**Comment by norbertpotocki** [comment]
Hi @seaward,

cfg4j was designed to use the JDK8 features from the very beginning. I can look into how much work would it be to extend the support to both JDK6 and 7.

I assume there's a reason why you can't upgrade to a more recent version of Java. Care to share what that is? Both versions 6 and 7 do not receive updates any more.

**Comment by seaward** [comment]
Thanks for reply @norbertpotocki ,

We are using JBoss EAP6 which works up to JDK7 only, sad...

**Comment by norbertpotocki** [comment]
@seaward - I did the necessary changes to make cfg4j work with Java 7. I'll let it sit over the weekend and release 4.2.0 early Monday. Is that good enough?

**Comment by seaward** [comment]
Great! Looking forward to it!!!
