### ISSUE TITLE
[feature request] Support the setting of configuration parameters via CLI

### ISSUE THREAD

**Issue by crimeminister** [cfg4j/cfg4j#134]
It's handy to be able to set and/or override configuration parameters from the command line, particularly for development. I'm not yet that familiar with the cfg4j internals but I imagine this would involve creating a source that accepted CLI param configuration settings for some getopt-like library, and the returned values could be used, merged with other settings, etc. in the usual way.

**Comment by norbertpotocki** [comment]
Hey @crimeminister,

Thanks for the suggestion - I'm already working on adding this feature in the release 4.3.0. It's being tracked as part of the #128 issue. I'm closing this one as a duplicate. Feel free to add more comments to the other issue.
