### ISSUE TITLE
Expose the established Consul connection in ConsulConfigurationSource

### ISSUE THREAD

**Issue by fromanator** [cfg4j/cfg4j#143]
Just wondering if you had any concerns or thoughts about exposing https://github.com/cfg4j/cfg4j/blob/master/cfg4j-consul/src/main/java/org/cfg4j/source/consul/ConsulConfigurationSource.java#L100 to be retrieved and used.

I figured it might be useful for use cases where you want a Consul client connection for something else, and you might as well use the one already established by cfg4j instead of making a new one.

**Comment by norbertpotocki** [comment]
That's a very reasonable idea but for now I was thinking of keeping the consul connector hidden from the users. Consul-client is a fairly new library and its interface may change. We may also decide to use some other library for communicating with consul  down the road. If we mix their interface with ours that won't be as easy anymore. It just doesn't feel worth it (combining that with the fact that gains from sharing the client probably aren't that big). Does that make sense?

**Comment by fromanator** [comment]
Yeah it totally makes sense, wanted to get your opinion on it before working on anything since I had similar reservations.
