### ISSUE TITLE
You can't use ClasspathConfigurationSource without an environment within a JAR

### ISSUE THREAD

**Issue by buckett** [cfg4j/cfg4j#154]
We package up a Java application into a fat JAR that contains all the application source code and the dependencies. This allows the application to be run as `java -jar myapp.jar`, however when doing this if I attempt to load a `ClasspathConfigurationSource` without having an environment set it blows up with:

    Caused by: org.cfg4j.source.context.environment.MissingEnvironmentException: Missing environment: Directory doesn't exist: 
	    at org.cfg4j.source.classpath.ClasspathConfigurationSource.getConfiguration(ClasspathConfigurationSource.java:109)
    	at org.cfg4j.source.compose.MergeConfigurationSource.getConfiguration(MergeConfigurationSource.java:62)
	    at org.cfg4j.provider.SimpleConfigurationProvider.getProperty(SimpleConfigurationProvider.java:91)
	    at org.cfg4j.provider.SimpleConfigurationProvider.getProperty(SimpleConfigurationProvider.java:64)

When running unpacked (from IDE) it all works correctly. Specifying and environment also fixes the problem, but this affects other configurations sources (`EnvironmentVariablesConfigurationSource`) and so I'd rather keep the environment empty.

**Comment by norbertpotocki** [comment]
Hey @buckett,

Thanks for reporting this! I'm having trouble reproducing the problem that you described. Could you post the sample code to github/gist or tell me how is your code different from this demo app? I'd really appreciate this :)

https://github.com/cfg4j/cfg4j-sample-apps/tree/master/classpath-bind

To run it (with a fat jar being built) clone the repo and the do the following:
> ./gradlew clean build
> cd cd classpath-bind/
> java -jar build/libs/classpath-bind-1.0.0-SNAPSHOT.jar

**Comment by norbertpotocki** [comment]
Would also you mind starring this project too - it makes it simpler for me to track all involved parties.

**Comment by buckett** [comment]
Thanks for the pointer to your examples.

I think the difference is that you're test application uses a spring boot and as a result the classloader that used is `org.springframework.boot.loader.LaunchedURLClassLoader`, in my application I'm just using a standard Java classloader  (I think it's a `sun.misc.Launcher$AppClassLoader`, but haven't got my code in the debugger again.

If I debug your sample application I can see the call to:

    getClass().getClassLoader().getResource(pathPrefix.toString()); 

working correctly when an empty string is passed in, however if I use the parent classloader instead and pass in the empty string I get a `null` back.

    getClass().getClassLoader().getParent().getResource("")

There's a some mention of this being a know issue on stackoverflow: http://stackoverflow.com/questions/21836950/urlclassloader-getresources-empty-resource-name-not-giving-roots-of-jars

**Comment by norbertpotocki** [comment]
Sorry for the delay. I managed to reproduce the problem. Thanks for fixing it!

What I also noticed is that the same problem occurs for other parameters (e.g. "/", ".", etc.). I'm going to do rethink how we handle environments since there's a few other issues with them too at the moment.

**Comment by norbertpotocki** [comment]
Released version [4.4.0](https://github.com/cfg4j/cfg4j/releases/tag/v.4.4.0). Let me know if you're still experiencing this problem :)
