### ISSUE TITLE
Missing non-String YAML properties

### ISSUE THREAD

**Issue by roded** [cfg4j/cfg4j#183]
Hi, 
I'd like to make sure this is an issue and I'm not missing something before submitting a PR.
`org.yaml.snakeyaml.Yaml` supports loading non-`String` properties, the canonical case being `Integer`s.
`YamlBasedPropertiesProvider` in turn, loads these properties into a `Properties` object which is a `String` only construct (`Properties` discourages `putAll` calls for this reason).
The result is that when trying to call `getProperty()` for a non-String property, null is returned.

**Comment by rtybase** [comment]
I have hit the same problem with Json counterpart. Yes, `getProperty()` is very basic. However, binding does the trick, although, if at least one attribute is misconfigures, the whole binding fails.

**Comment by roded** [comment]
Indeed it works great with binding.
I'll close this then.
