### ISSUE TITLE
Support nested object bindings

### ISSUE THREAD

**Issue by remmeier** [cfg4j/cfg4j#186]
Class X{
  Y a
}

Class Y{
  String b
}

should map the config key "a.b". The current binding mechanism with a simple object is too simplistic.

**Comment by remmeier** [comment]
is there an interest for a PR?

**Comment by fabriziocucci** [comment]
Is this the same as #178 ? 

BTW, I was working on a very similar [library](https://github.com/fabriziocucci/yacl4j) entirely based on Jackson which support nested configurations by default. It's **way less mature** than cfg4j but if you only need nested configurations you could give it a try!

**Comment by remmeier** [comment]
right...
