### ISSUE TITLE
Make ConsulConfigurationSource a public class

### ISSUE THREAD

**Issue by shudas** [cfg4j/cfg4j#199]
ConsulConfigurationSource is package private but it is the return value of the public function, ConsulConfigurationSourceBuilder::build. This causes problems when using kotlin b/c kotlin cannot assign any variable to type ConsulConfigurationSource since it is package private. Since ConsulConfigurationSourceBuilder::build returns an instance of ConsulConfigurationSource, we should make ConsulConfigurationSource a public class.

**Comment by shudas** [comment]
Fixed by https://github.com/cfg4j/cfg4j/pull/198

**Comment by norbertpotocki** [comment]
Thanks for addressing this!
