### ISSUE TITLE
How to use with environment variables?

### ISSUE THREAD

**Issue by Paxa** [cfg4j/cfg4j#263]
Any documentation on how it maps env variables to config values?

**Comment by aaukhatov** [comment]
I'm also confused when try to use environment variables

**Comment by aaukhatov** [comment]
Documentation don't have any information about it.

**Comment by aaukhatov** [comment]
At first I exported env var:
```
export MY_SERVICE_URI=http://localhost:9900/
```
Then try to use it...
There is my code snippet:
```java
ConfigurationSource envSource = new EnvironmentVariablesConfigurationSource();
ConfigurationProvider provider = new ConfigurationProviderBuilder()
                .withConfigurationSource(envSource)
                .build();
```

```java
provider.getProperty("my.service.uri", String.class); // then throws exception...
```

**Comment by aaukhatov** [comment]
Hi @Paxa!
I was debugging and found env vars resolving are case sensitive.
For the example above it means `MY_SERVICE_URI ` env will resolve as `MY.SERVICE.URI `.

**Comment by Paxa** [comment]
THanks alot for explaining! Appreciate it

> I was debugging and found env vars resolving are case sensitive.

I wish it was configurable
