### ISSUE TITLE
Support configuration merge

### ISSUE THREAD

**Issue by norbertpotocki** [cfg4j/cfg4j#28]

**Comment by arminbalalaie** [comment]
@norbertpotocki I was trying to use the configuration merging feature. I noticed a problem. The environment values can be different for different configuration sources and it seems the current implementation uses one environment for all of the sources. I believe for having a functional merging feature, it is needed to correspond different environment objects to different configuration sources. It'd be nice to have a default merged configuration as well. Something like application.yml in Classpath > application.yml in Jar folder > Environment Vars.

Anyways, I believe configuration profiles work way better than environments. This is the approach that spring boot is taking. https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-profiles.html

**Comment by arminbalalaie** [comment]
@norbertpotocki As a followup, I think it's really better to have just one environment (or multiple profiles) and add other parameters to parameterize different configuration sources based on that specific environment. It just doesn't make sense to have different ways of specifying environments for different config sources. For example, for File-based configuration, it is possible to add a constructor to receive a root path for config files. Then, the exact config file for test environment can be something like /root/path/test/application.properties.
